### ISSUE TITLE
Cannot chose Account to Modify

### ISSUE THREAD

**Issue by r4p70rk4m** [agallego-css/ExoGraphGUI#10]
Hello Guys, 

Im an EXO Specialist working for Microsoft Support. I need to delete all contents of a particular folder within a mailbox. I have found that the best way to do this given my current situation is to move data from the folder I want to empty to the deletions folder.

ExoGraphGUI was the answer as nothing else is working well enough. The problem I have is that I ran:

Install-Module ExoGraphGUI
Update-Module ExoGraphGUI
Start-ExoGraphGUI

This prompted a request for Admin Consent which I provided.

However now the app seems to be bound to the admin account, I cannot chose another mailbox to perform operations on. What am I doing wrong?

**Comment by DrummerViking** [comment]
usually when opening powershell, if there is any existing connection in your cache, you can run:
get-MgContext

if you see your admin account cached, just simply disconnect from it:
Disconnect-MgGraph

later when running the EXOGraphGUI app, it will prompt for credentials (and you can enter the mailbox credential you want to work with).

**Comment by r4p70rk4m** [comment]
Worked perfectly, thank you.
